/**
 * Global site configuration.
 *
 * Phase 2 note: `url` is used for canonical links, sitemap.xml and OG tags.
 * Replace with the real production domain before launch.
 */
export const siteConfig = {
  name: "AI Tech",
  tagline: "Computer tutorials you can actually follow.",
  url: "https://techhow.pages.dev",
  locale: "en",
  /** Default social/OG image (generated by app/opengraph-image.tsx). */
  ogImage: "/opengraph-image",
  /** Newsletter endpoint — Phase 3 wires this to a real provider. */
  newsletter: {
    enabled: true,
    provider: "local" as "local" | "mailchimp" | "beehiiv" | "substack",
  },
  /** Ad network — Phase 3 replaces placeholder slots with a real snippet. */
  ads: {
    enabled: false,
    network: "adsense" as "adsense" | "none",
    clientId: "",
  },
  i18n: {
    /** Languages the routing/i18n architecture supports. */
    locales: ["en", "de", "fr", "es", "it", "pt", "nl", "pl", "tr"],
    /** Locales with actual translations shipped at launch. */
    default: "en" as const,
    enabled: ["en"],
  },
};

export const NAV_CATEGORIES = [
  { slug: "windows", label: "Windows" },
  { slug: "macos", label: "macOS" },
  { slug: "hardware", label: "Hardware" },
  { slug: "software", label: "Software" },
  { slug: "internet", label: "Internet" },
  { slug: "security", label: "Security" },
  { slug: "coding", label: "Coding" },
  { slug: "ai", label: "AI & Automation" },
] as const;

/** Top-level nav: aggregate pages + category pages. */
export const NAV_LINKS = [
  { href: "/tutorials", label: "All Tutorials" },
  { href: "/trending", label: "Most Popular" },
  ...NAV_CATEGORIES.map((c) => ({ href: `/${c.slug}`, label: c.label })),
];
